#!/bin/bash
#Lists all chrooted processes. First parameter is chroot directory. Script might need to run as root.
#Techniques originally released by other authors at http://forums.grsecurity.net/viewtopic.php?f=3&t=1632 .

. ubiquitous_bash.sh

CHROOT=$(getAbsoluteLocation "$1")
PROCS=""
for p in `ps -o pid -A`; do
	if [ "`readlink /proc/$p/root`" = "$CHROOT" ]; then
		PROCS="$PROCS $p"
	fi
done
echo "$PROCS"
